package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"
	"obserbooks/graph/model"
	database "obserbooks/infrastructure/mysql"
	repositories "obserbooks/infrastructure/repositories/book"
	"obserbooks/usecases/boundaries"
)

// TODO
// ReadingMemoとのリレーション
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	panic(fmt.Errorf("not implemented: Books - books"))
}

var _ boundaries.BookInputBoundary = &BookInteractor{}

type BookInteractor struct {
	bookRepository repositories.BookRepository
	db             database.DB
}

func NewBookInteractor(bookRepository repositories.BookRepository) *BookInteractor {
	return &BookInteractor{
		bookRepository: bookRepository,
	}
}
